trigger:
- tests/playwright
pool:
  vmImage: 'windows-latest'
steps:
- script: echo Running azure-pipelines.yml...
  displayName: 'Run a one-line script'
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'nodetool 16.x'
- task: Npm@1
  inputs:
    command: 'ci'
- task: CmdLine@2
  inputs:
    script: 'npx playwright install --with-deps'
- task: CmdLine@2
  inputs:
    script: 'set CI=true && echo %CI% && npx playwright test'
    
- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
        searchFolder: 'playwright-report'
        testResultsFormat: 'JUnit'
        testResultsFiles: 'results.xml' 
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'My End-To-End Tests'
  condition: succeededOrFailed()
  